# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: business_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x62usiness_service.proto\x12\x08\x62usiness\"\x1d\n\x0f\x42usinessRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\xcc\x02\n\x12NewBusinessRequest\x12\x12\n\nbusinessid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06rating\x18\x03 \x01(\x02\x12\x14\n\x0creview_count\x18\x04 \x01(\x05\x12\x0f\n\x07\x61\x64\x64ress\x18\x05 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x06 \x01(\t\x12\x0c\n\x04\x63ity\x18\x07 \x01(\t\x12\r\n\x05state\x18\x08 \x01(\t\x12\x0f\n\x07\x63ountry\x18\t \x01(\t\x12\x10\n\x08zip_code\x18\n \x01(\t\x12\x10\n\x08latitude\x18\x0b \x01(\x02\x12\x11\n\tlongitude\x18\x0c \x01(\x02\x12\r\n\x05phone\x18\r \x01(\t\x12\r\n\x05price\x18\x0e \x01(\t\x12\x11\n\timage_url\x18\x0f \x01(\t\x12\x0b\n\x03url\x18\x10 \x01(\t\x12\x10\n\x08\x64istance\x18\x11 \x01(\x02\x12\x16\n\x0e\x62usiness_hours\x18\x12 \x01(\t\"\xd6\x02\n\x10\x42usinessResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nbusinessid\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0e\n\x06rating\x18\x04 \x01(\x02\x12\x14\n\x0creview_count\x18\x05 \x01(\x05\x12\x0f\n\x07\x61\x64\x64ress\x18\x06 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x07 \x01(\t\x12\x0c\n\x04\x63ity\x18\x08 \x01(\t\x12\r\n\x05state\x18\t \x01(\t\x12\x0f\n\x07\x63ountry\x18\n \x01(\t\x12\x10\n\x08zip_code\x18\x0b \x01(\t\x12\x10\n\x08latitude\x18\x0c \x01(\x02\x12\x11\n\tlongitude\x18\r \x01(\x02\x12\r\n\x05phone\x18\x0e \x01(\t\x12\r\n\x05price\x18\x0f \x01(\t\x12\x11\n\timage_url\x18\x10 \x01(\t\x12\x0b\n\x03url\x18\x11 \x01(\t\x12\x10\n\x08\x64istance\x18\x12 \x01(\x02\x12\x16\n\x0e\x62usiness_hours\x18\x13 \x01(\t2\xa0\x01\n\x0f\x42usinessService\x12\x44\n\x0bGetBusiness\x12\x19.business.BusinessRequest\x1a\x1a.business.BusinessResponse\x12G\n\x0b\x41\x64\x64\x42usiness\x12\x1c.business.NewBusinessRequest\x1a\x1a.business.BusinessResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'business_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_BUSINESSREQUEST']._serialized_start=36
  _globals['_BUSINESSREQUEST']._serialized_end=65
  _globals['_NEWBUSINESSREQUEST']._serialized_start=68
  _globals['_NEWBUSINESSREQUEST']._serialized_end=400
  _globals['_BUSINESSRESPONSE']._serialized_start=403
  _globals['_BUSINESSRESPONSE']._serialized_end=745
  _globals['_BUSINESSSERVICE']._serialized_start=748
  _globals['_BUSINESSSERVICE']._serialized_end=908
# @@protoc_insertion_point(module_scope)
