# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import business_service_pb2 as business__service__pb2


class BusinessServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBusiness = channel.unary_unary(
                '/business.BusinessService/GetBusiness',
                request_serializer=business__service__pb2.BusinessRequest.SerializeToString,
                response_deserializer=business__service__pb2.BusinessResponse.FromString,
                )
        self.AddBusiness = channel.unary_unary(
                '/business.BusinessService/AddBusiness',
                request_serializer=business__service__pb2.NewBusinessRequest.SerializeToString,
                response_deserializer=business__service__pb2.BusinessResponse.FromString,
                )


class BusinessServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBusiness(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBusiness(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BusinessServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBusiness': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBusiness,
                    request_deserializer=business__service__pb2.BusinessRequest.FromString,
                    response_serializer=business__service__pb2.BusinessResponse.SerializeToString,
            ),
            'AddBusiness': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBusiness,
                    request_deserializer=business__service__pb2.NewBusinessRequest.FromString,
                    response_serializer=business__service__pb2.BusinessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'business.BusinessService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BusinessService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBusiness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/business.BusinessService/GetBusiness',
            business__service__pb2.BusinessRequest.SerializeToString,
            business__service__pb2.BusinessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddBusiness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/business.BusinessService/AddBusiness',
            business__service__pb2.NewBusinessRequest.SerializeToString,
            business__service__pb2.BusinessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
