# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import business_service_pb2 as business__service__pb2


class BusinessServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBusiness = channel.unary_unary(
                '/business.BusinessService/GetBusiness',
                request_serializer=business__service__pb2.BusinessRequest.SerializeToString,
                response_deserializer=business__service__pb2.BusinessResponse.FromString,
                )
        self.AddBusiness = channel.unary_unary(
                '/business.BusinessService/AddBusiness',
                request_serializer=business__service__pb2.NewBusinessRequest.SerializeToString,
                response_deserializer=business__service__pb2.BusinessResponse.FromString,
                )
        self.GetBusinessByName = channel.unary_unary(
                '/business.BusinessService/GetBusinessByName',
                request_serializer=business__service__pb2.BusinessByNameRequest.SerializeToString,
                response_deserializer=business__service__pb2.BusinessResponse.FromString,
                )
        self.GetBusinessByLocation = channel.unary_unary(
                '/business.BusinessService/GetBusinessByLocation',
                request_serializer=business__service__pb2.BusinessByLocationRequest.SerializeToString,
                response_deserializer=business__service__pb2.BusinessListResponse.FromString,
                )
        self.GetBusinessByCategory = channel.unary_unary(
                '/business.BusinessService/GetBusinessByCategory',
                request_serializer=business__service__pb2.CategoryRequest.SerializeToString,
                response_deserializer=business__service__pb2.BusinessListResponse.FromString,
                )
        self.GetBusinessByRating = channel.unary_unary(
                '/business.BusinessService/GetBusinessByRating',
                request_serializer=business__service__pb2.RatingRequest.SerializeToString,
                response_deserializer=business__service__pb2.BusinessListResponse.FromString,
                )
        self.GetBusinessByProximity = channel.unary_unary(
                '/business.BusinessService/GetBusinessByProximity',
                request_serializer=business__service__pb2.BusinessByProximityRequest.SerializeToString,
                response_deserializer=business__service__pb2.BusinessListResponse.FromString,
                )
        self.GetTrendingBusinesses = channel.unary_unary(
                '/business.BusinessService/GetTrendingBusinesses',
                request_serializer=business__service__pb2.TrendingRequest.SerializeToString,
                response_deserializer=business__service__pb2.BusinessListResponse.FromString,
                )


class BusinessServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBusiness(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBusiness(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBusinessByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBusinessByLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBusinessByCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBusinessByRating(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBusinessByProximity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrendingBusinesses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BusinessServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBusiness': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBusiness,
                    request_deserializer=business__service__pb2.BusinessRequest.FromString,
                    response_serializer=business__service__pb2.BusinessResponse.SerializeToString,
            ),
            'AddBusiness': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBusiness,
                    request_deserializer=business__service__pb2.NewBusinessRequest.FromString,
                    response_serializer=business__service__pb2.BusinessResponse.SerializeToString,
            ),
            'GetBusinessByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBusinessByName,
                    request_deserializer=business__service__pb2.BusinessByNameRequest.FromString,
                    response_serializer=business__service__pb2.BusinessResponse.SerializeToString,
            ),
            'GetBusinessByLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBusinessByLocation,
                    request_deserializer=business__service__pb2.BusinessByLocationRequest.FromString,
                    response_serializer=business__service__pb2.BusinessListResponse.SerializeToString,
            ),
            'GetBusinessByCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBusinessByCategory,
                    request_deserializer=business__service__pb2.CategoryRequest.FromString,
                    response_serializer=business__service__pb2.BusinessListResponse.SerializeToString,
            ),
            'GetBusinessByRating': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBusinessByRating,
                    request_deserializer=business__service__pb2.RatingRequest.FromString,
                    response_serializer=business__service__pb2.BusinessListResponse.SerializeToString,
            ),
            'GetBusinessByProximity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBusinessByProximity,
                    request_deserializer=business__service__pb2.BusinessByProximityRequest.FromString,
                    response_serializer=business__service__pb2.BusinessListResponse.SerializeToString,
            ),
            'GetTrendingBusinesses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrendingBusinesses,
                    request_deserializer=business__service__pb2.TrendingRequest.FromString,
                    response_serializer=business__service__pb2.BusinessListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'business.BusinessService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BusinessService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBusiness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/business.BusinessService/GetBusiness',
            business__service__pb2.BusinessRequest.SerializeToString,
            business__service__pb2.BusinessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddBusiness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/business.BusinessService/AddBusiness',
            business__service__pb2.NewBusinessRequest.SerializeToString,
            business__service__pb2.BusinessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBusinessByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/business.BusinessService/GetBusinessByName',
            business__service__pb2.BusinessByNameRequest.SerializeToString,
            business__service__pb2.BusinessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBusinessByLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/business.BusinessService/GetBusinessByLocation',
            business__service__pb2.BusinessByLocationRequest.SerializeToString,
            business__service__pb2.BusinessListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBusinessByCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/business.BusinessService/GetBusinessByCategory',
            business__service__pb2.CategoryRequest.SerializeToString,
            business__service__pb2.BusinessListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBusinessByRating(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/business.BusinessService/GetBusinessByRating',
            business__service__pb2.RatingRequest.SerializeToString,
            business__service__pb2.BusinessListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBusinessByProximity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/business.BusinessService/GetBusinessByProximity',
            business__service__pb2.BusinessByProximityRequest.SerializeToString,
            business__service__pb2.BusinessListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTrendingBusinesses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/business.BusinessService/GetTrendingBusinesses',
            business__service__pb2.TrendingRequest.SerializeToString,
            business__service__pb2.BusinessListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
