# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'user_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\x12\x04user\"Y\n\x13RegisterUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0bpreferences\x18\x04 \x01(\t\"Q\n\x14RegisterUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x17\n\x0frecommendations\x18\x03 \x01(\t\"3\n\x10LoginUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"n\n\x11LoginUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\r\n\x05token\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\x05\x12\x17\n\x0frecommendations\x18\x05 \x01(\t\"(\n\x15GetUserProfileRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"V\n\x16GetUserProfileResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0bpreferences\x18\x04 \x01(\t\"N\n\x18UpdateUserProfileRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0bpreferences\x18\x03 \x01(\t\"=\n\x19UpdateUserProfileResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\"$\n\x11\x44\x65leteUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"6\n\x12\x44\x65leteUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\xf6\x02\n\x0bUserService\x12\x45\n\x0cRegisterUser\x12\x19.user.RegisterUserRequest\x1a\x1a.user.RegisterUserResponse\x12<\n\tLoginUser\x12\x16.user.LoginUserRequest\x1a\x17.user.LoginUserResponse\x12K\n\x0eGetUserProfile\x12\x1b.user.GetUserProfileRequest\x1a\x1c.user.GetUserProfileResponse\x12T\n\x11UpdateUserProfile\x12\x1e.user.UpdateUserProfileRequest\x1a\x1f.user.UpdateUserProfileResponse\x12?\n\nDeleteUser\x12\x17.user.DeleteUserRequest\x1a\x18.user.DeleteUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERUSERREQUEST']._serialized_start=28
  _globals['_REGISTERUSERREQUEST']._serialized_end=117
  _globals['_REGISTERUSERRESPONSE']._serialized_start=119
  _globals['_REGISTERUSERRESPONSE']._serialized_end=200
  _globals['_LOGINUSERREQUEST']._serialized_start=202
  _globals['_LOGINUSERREQUEST']._serialized_end=253
  _globals['_LOGINUSERRESPONSE']._serialized_start=255
  _globals['_LOGINUSERRESPONSE']._serialized_end=365
  _globals['_GETUSERPROFILEREQUEST']._serialized_start=367
  _globals['_GETUSERPROFILEREQUEST']._serialized_end=407
  _globals['_GETUSERPROFILERESPONSE']._serialized_start=409
  _globals['_GETUSERPROFILERESPONSE']._serialized_end=495
  _globals['_UPDATEUSERPROFILEREQUEST']._serialized_start=497
  _globals['_UPDATEUSERPROFILEREQUEST']._serialized_end=575
  _globals['_UPDATEUSERPROFILERESPONSE']._serialized_start=577
  _globals['_UPDATEUSERPROFILERESPONSE']._serialized_end=638
  _globals['_DELETEUSERREQUEST']._serialized_start=640
  _globals['_DELETEUSERREQUEST']._serialized_end=676
  _globals['_DELETEUSERRESPONSE']._serialized_start=678
  _globals['_DELETEUSERRESPONSE']._serialized_end=732
  _globals['_USERSERVICE']._serialized_start=735
  _globals['_USERSERVICE']._serialized_end=1109
# @@protoc_insertion_point(module_scope)
